name: deploy-blog

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
  workflow_dispatch:

# This job installs dependencies and builds the blog
jobs:
  deploy-blog:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Removes current blog files
    - name: Removes current blog files
      run: |
        ablog clean -w docs

    # Removes current blog files
    - name: Build blog
      run: |
        ablog build -w docs
    
    # Adds .nojekyll file
    - name: Add .nojekyll
      run: |
        cat > docs/.nojekyll

    # Commit all changed files back to the repository
    - uses: stefanzweifel/git-auto-commit-action@v5